url: https://blackicesystems.github.io
baseurl: https://blackicesystems.github.io/

# Site settings
title: Awesome Title
email: sales@blackicesystems.com
description: "Black Ice Systems are leading consultants in functional safety and risk based in Perth, Western Australia."

# Team names, titles and social links
people:
- name: Matt Goode
  pic: 1
  position: Principal Consultant
  social:
    - title: linkedin
      url: https://au.linkedin.com/in/mattcgoode

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: linkedin
    url: https://www.linkedin.com/company/black-ice-systems


# Postal address (add as many lines as necessary)
address:
  - line: Suite 5, 1 Brewer Street
  - line: Perth, Western Australia, 6000

# Build settings
markdown: kramdown
permalink: pretty